<?php

namespace App\Http\Controllers;

use App\Hosting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OldHomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tests = DB::table('hostings_checked')->get();
        $http_code = $this->http_codes_explonation();

        return view('pages.home', compact('tests', 'http_code'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return *404* 'PageNotFound'
     */
    public function register() 
    {
        abort(404, 'Page Not Found');
    }

    /**
     * Return http_codes with explonation
     *
     * @return Array
     */
    public function http_codes_explonation() 
    {
        return [
            0   => 'Error: No status code',
            100 => 'Informational: Continue',
            101 => 'Informational: Switching Protocols',
            102 => 'Informational: Processing',
            200 => 'Successful: OK',
            201 => 'Successful: Created',
            202 => 'Successful: Accepted',
            203 => 'Successful: Non-Authoritative Information',
            204 => 'Successful: No Content',
            205 => 'Successful: Reset Content',
            206 => 'Successful: Partial Content',
            207 => 'Successful: Multi-Status',
            208 => 'Successful: Already Reported',
            226 => 'Successful: IM Used',
            300 => 'Redirection: Multiple Choices',
            301 => 'Redirection: Moved Permanently',
            302 => 'Redirection: Found',
            303 => 'Redirection: See Other',
            304 => 'Redirection: Not Modified',
            305 => 'Redirection: Use Proxy',
            306 => 'Redirection: Switch Proxy',
            307 => 'Redirection: Temporary Redirect',
            308 => 'Redirection: Permanent Redirect',
            400 => 'Client Error: Bad Request',
            401 => 'Client Error: Unauthorized',
            402 => 'Client Error: Payment Required',
            403 => 'Client Error: Forbidden',
            404 => 'Client Error: Not Found',
            405 => 'Client Error: Method Not Allowed',
            406 => 'Client Error: Not Acceptable',
            407 => 'Client Error: Proxy Authentication Required',
            408 => 'Client Error: Request Timeout',
            409 => 'Client Error: Conflict',
            410 => 'Client Error: Gone',
            411 => 'Client Error: Length Required',
            412 => 'Client Error: Precondition Failed',
            413 => 'Client Error: Request Entity Too Large',
            414 => 'Client Error: Request-URI Too Long',
            415 => 'Client Error: Unsupported Media Type',
            416 => 'Client Error: Requested Range Not Satisfiable',
            417 => 'Client Error: Expectation Failed',
            418 => 'Client Error: I\'m a teapot',
            419 => 'Client Error: Authentication Timeout',
            420 => 'Client Error: Enhance Your Calm',
            420 => 'Client Error: Method Failure',
            422 => 'Client Error: Unprocessable Entity',
            423 => 'Client Error: Locked',
            424 => 'Client Error: Failed Dependency',
            424 => 'Client Error: Method Failure',
            425 => 'Client Error: Unordered Collection',
            426 => 'Client Error: Upgrade Required',
            428 => 'Client Error: Precondition Required',
            429 => 'Client Error: Too Many Requests',
            431 => 'Client Error: Request Header Fields Too Large',
            444 => 'Client Error: No Response',
            449 => 'Client Error: Retry With',
            450 => 'Client Error: Blocked by Windows Parental Controls',
            451 => 'Client Error: Redirect',
            451 => 'Client Error: Unavailable For Legal Reasons',
            494 => 'Client Error: Request Header Too Large',
            495 => 'Client Error: Cert Error',
            496 => 'Client Error: No Cert',
            497 => 'Client Error: HTTP to HTTPS',
            499 => 'Client Error: Client Closed Request',
            500 => 'Server Error: Internal Server Error',
            501 => 'Server Error: Not Implemented',
            502 => 'Server Error: Bad Gateway',
            503 => 'Server Error: Service Unavailable',
            504 => 'Server Error: Gateway Timeout',
            505 => 'Server Error: HTTP Version Not Supported',
            506 => 'Server Error: Variant Also Negotiates',
            507 => 'Server Error: Insufficient Storage',
            508 => 'Server Error: Loop Detected',
            509 => 'Server Error: Bandwidth Limit Exceeded',
            510 => 'Server Error: Not Extended',
            511 => 'Server Error: Network Authentication Required',
            598 => 'Server Error: Network read timeout error',
            599 => 'Server Error: Network connect timeout error',
        ];
    }

    public function findItOut() 
    {
        $all = ['takykcesme.com.tm',
'ibcorp-saderatbank.com.tm',
'iuhd.edu.tm',
'horjun.com.tm',
'balkanagyzsuw.gov.tm',
'gepreg.gov.tm',
'turkmenaltyn.com.tm',
'aktam.com.tm',
'tdei.edu.tm',
'dahua.com.tm',
'awtomenzil.gov.tm',
'avtoyollar.gov.tm',
'akgap.com.tm',
'turkmenhemrasy.gov.tm',
'balary.com.tm',
'constructionprice.gov.tm',
'giper.com.tm',
'aksaray.com.tm',
'mlsp.gov.tm',
'bazar.com.tm',
'nokat.com.tm',
'ashgabathyakimlik.gov.tm',
'tdmi.edu.tm',
'turkmenatlary.gov.tm',
'lebaptravel.gov.tm',
'strateg.gov.tm',
'coca-cola.com.tm',
'cci.com.tm',
'turkmenpolat-bn.gov.tm',
'industry.gov.tm',
'tugu.gov.tm',
'greatsilkroadconference2018.gov.tm',
'turkmendomain.gov.tm',
'onko.gov.tm',
'kerwen.gov.tm',
'terminal.gov.tm',
'teronum.com.tm',
'ecifas.gov.tm',
'agb.com.tm',
'harmantm.com.tm',
'muk.com.tm',
'hazarbalkan.com.tm',
'turkmen-kaliy.com.tm',
'altyn-kanun.com.tm',
'fykmh.gov.tm',
'islenen.com.tm',
'turkmensyyahat.gov.tm',
'danaproject.com.tm',
'tigirli-mahabat.com.tm',
'yarish.com.tm',
'sahysoltan.com.tm',
'dashdemir.com.tm',
'merdanatv.com.tm',
'hazyna.com.tm',
'dashoguztravel.gov.tm',
'siyahatour.com.tm',
'dashoguzmuseum.gov.tm',
'gala.com.tm',
'dermanhana.com.tm',
'yovshan.com.tm',
'apteka.com.tm',
'dovletkitaphana.gov.tm',
'caa.gov.tm',
'biznes.com.tm',
'business.com.tm',
'bt.com.tm',
'online.tm',
'tia.gov.tm',
'getir.com.tm',
'marykitaphana.com.tm',
'museum.gov.tm',
'turkmenteatrlary.gov.tm',
'turkmenistan.gov.tm',
'ashgabat2017.gov.tm',
'politehnikum.edu.tm',
'seysmostroy.gov.tm',
'artmuseum.gov.tm',
'senagatbank.gov.tm',
'arzan.com.tm',
'ARZAN.COM.TM',
'milligosun.gov.tm',
'dost.com.tm',
'oilgas.gov.tm',
'halkbank.gov.tm',
'st.com.tm',
'tdp.gov.tm',
'tmembassy.gov.tm',
'tmconsulate.gov.tm',
'mission.gov.tm',
'turkmenturkbank.gov.tm',
'tkm-derman.gov.tm',
'awtoulag.gov.tm',
'cultureofturkmenistan.gov.tm',
'tdob.gov.tm',
'minenergo.gov.tm',
'tstb.gov.tm',
'meteo.gov.tm',
'construction.gov.tm',
'tkamm.gov.tm',
'zenan.gov.tm',
'dayhanbank.gov.tm',
'insurance.gov.tm',
'mfa.gov.tm',
'tfeb.gov.tm',
'tdh.gov.tm',
'tbbank.gov.tm',
'minagri.gov.tm',
'turkmenhali.gov.tm',
'turkmentextile.gov.tm',
'stat.gov.tm',
'minfin.gov.tm',
'wekilbazardokma.gov.tm',
'mintradefer.gov.tm',
'migration.gov.tm',
'minjust.gov.tm',
'turkmencosmos.gov.tm',
'tgymj.gov.tm',
'exchange.gov.tm',
'turkmenstandartlary.gov.tm',
'saglykhm.gov.tm',
'Saglykhm.gov.tm',
'cci.gov.tm',
'www.cci.gov.tm',
'tax.gov.tm',
'turkmenexport.gov.tm',
'bayramalytextilex.gov.tm',
'yashlar.gov.tm',
'turkmenfmd.gov.tm',
'turkmenhimiya.gov.tm',
'natureprotection.gov.tm',
'science.gov.tm',
'saylav.gov.tm',
'influ.gov.tm',
'acs.gov.tm',
'mpi.gov.tm',
'ib.gov.tm',
'mb.gov.tm',
'customs.gov.tm',
'turkmenpost.gov.tm',
'mincom.gov.tm',
'awazasport.gov.tm',
'modelleroyi.gov.tm',
'etalon.gov.tm',
'ashgabatairport.gov.tm',
'msy.gov.tm',
'metbugat.gov.tm',
'railway.gov.tm',
'maryairport.gov.tm',
'serhetabat-dovletabat.gov.tm',
'serhetabat-dovletabat.gov.tm',
'scct.gov.tm',
'archabilhotel.gov.tm',
'turkmentv.gov.tm',
'tulm.gov.tm',
'dashoguzairport.gov.tm',
'chagalar-kitaphana.gov.tm',
'marymuseum.gov.tm',
'cefavaza2019.gov.tm',
'ttf.gov.tm',
'lebapmuseum.gov.tm',
'lebapkitap.gov.tm',
'balkanmuseum.gov.tm',
'deg.gov.tm',
'made-in-turkmenistan.com.tm',
'mazam.com.tm',
'mothercare.com.tm',
'mitsubishi.com.tm',
'tiztoleg.com.tm',
'turkmenwater.com.tm',
'muse.com.tm',
'sharafyabi.com.tm',
'almaz-sheyh.com.tm',
'archa.com.tm',
'gocdas.com.tm',
'tjk.com.tm',
'rysgalbank.com.tm',
'sirius8.com.tm',
'nbp.com.tm',
'yosm.com.tm',
'turkmenbashiairport.com.tm',
'tff.com.tm',
'yashyldunya.com.tm',
'galam.com.tm',
'seyranasyyakhat.com.tm',
'telekeci.com.tm',
'doehler.com.tm',
'hasyl.com.tm',
'emart.com.tm',
'tmcars.com.tm',
'marysiyakhat.com.tm',
'bdo.com.tm',
'gululkam.com.tm',
'akgar.com.tm',
'dana.com.tm',
'bizbarde.com.tm',
'akyaprak.com.tm',
'cct.com.tm',
'nurteh.com.tm',
'gnbookstore.com.tm',
'burgutdesign.com.tm',
'sadaplast.com.tm',
'goshagumry.com.tm',
'tizulgam.com.tm',
'hekem.com.tm',
'salkyn.com.tm',
'bakgalhukuk.com.tm',
'aydyn-mahabat.com.tm',
'teykent.com.tm',
'saglyktm.com.tm',
'akbulut.com.tm',
'hyzmatdashlar.com.tm',
'ah-insurance.com.tm',
'trsosh.edu.tm',
'gujurlynesil.edu.tm',
'dana.edu.tm',
'ticit.edu.tm',
'dayan.edu.tm',
'tdmai.edu.tm',
'ashgabat2018.com',
'telecom.tm',
'wm.online.tm',
'orient.tm'];

$have = ['telecom.tm',
'mincom.gov.tm',
'industry.gov.tm',
'akgap.com.tm',
'archa.com.tm',
'almaz-sheyh.com.tm',
'sharafyabi.com.tm',
'muse.com.tm',
'tiztoleg.com.tm',
'dahua.com.tm',
'aktam.com.tm',
'tdp.gov.tm',
'tdei.edu.tm',
'mitsubishi.com.tm',
'mazam.com.tm',
'made-in-turkmenistan.com.tm',
'democratic-party.gov.tm',
'dashoguzairport.gov.tm',
'st.com.tm',
'gepreg.gov.tm',
'dost.com.tm',
'arzan.com.tm',
'politehnikum.edu.tm',
'sowda.com.tm',
'cultureofturkmenistan.gov.tm',
'museum.gov.tm',
'turkmenistan.gov.tm',
'ashgabat2017.gov.tm',
'seysmostroy.gov.tm',
'senagatbank.gov.tm',
'milligosun.gov.tm',
'oilgas.gov.tm',
'halkbank.gov.tm',
'turkmenaltyn.com.tm',
'tmembassy.gov.tm',
'tmconsulate.gov.tm',
'mission.gov.tm',
'awtomenzil.gov.tm',
'turkmenturkbank.gov.tm',
'tkm-derman.gov.tm',
'awtoulag.gov.tm',
'tdob.gov.tm',
'avtoyollar.gov.tm',
'turkmenhemrasy.gov.tm',
'constructionprice.gov.tm',
'minenergo.gov.tm',
'tstb.gov.tm',
'meteo.gov.tm',
'construction.gov.tm',
'tkamm.gov.tm',
'zenan.gov.tm',
'dayhanbank.gov.tm',
'insurance.gov.tm',
'mfa.gov.tm',
'tfeb.gov.tm',
'tdh.gov.tm',
'tbbank.gov.tm',
'minagri.gov.tm',
'turkmenhali.gov.tm',
'turkmentextile.gov.tm',
'stat.gov.tm',
'mlsp.gov.tm',
'minfin.gov.tm',
'wekilbazardokma.gov.tm',
'mintradefer.gov.tm',
'migration.gov.tm',
'minjust.gov.tm',
'turkmencosmos.gov.tm',
'tgymj.gov.tm',
'exchange.gov.tm',
'tourism.gov.tm',
'trsosh.edu.tm',
'turkmenstandartlary.gov.tm',
'saglykhm.gov.tm',
'cci.gov.tm',
'rysgalbank.com.tm',
'bazar.com.tm',
'tax.gov.tm',
'turkmenexport.gov.tm',
'bayramalytextilex.gov.tm',
'nokat.com.tm',
'yashlar.gov.tm',
'turkmenfmd.gov.tm',
'ashgabathyakimlik.gov.tm',
'tdmi.edu.tm',
'gujurlynesil.edu.tm',
'turkmenatlary.gov.tm',
'turkmenhimiya.gov.tm',
'sirius8.com.tm',
'natureprotection.gov.tm',
'lebaptravel.gov.tm',
'strateg.gov.tm',
'coca-cola.com.tm',
'cci.com.tm',
'nbp.com.tm',
'turkmenpolat-bn.gov.tm',
'science.gov.tm',
'industry.gov.tm',
'saylav.gov.tm',
'influ.gov.tm',
'tugu.gov.tm',
'greatsilkroadconference2018.gov.tm',
'turkmendomain.gov.tm',
'acs.gov.tm',
'mpi.gov.tm',
'ib.gov.tm',
'mb.gov.tm',
'onko.gov.tm',
'yosm.com.tm',
'customs.gov.tm',
'kerwen.gov.tm',
'turkmenpost.gov.tm',
'mincom.gov.tm',
'turkmenbashiairport.com.tm',
'tff.com.tm',
'terminal.gov.tm',
'yashyldunya.com.tm',
'awazasport.gov.tm',
'galam.com.tm',
'seyranasyyakhat.com.tm',
'teronum.com.tm',
'ing.gov.tm',
'ecifas.gov.tm',
'telekeci.com.tm',
'agb.com.tm',
'harmantm.com.tm',
'muk.com.tm',
'modelleroyi.gov.tm',
'etalon.gov.tm',
'doehler.com.tm',
'hazarbalkan.com.tm',
'hasyl.com.tm',
'emart.com.tm',
'tmcars.com.tm',
'marysiyakhat.com.tm',
'bdo.com.tm',
'turkmen-kaliy.com.tm',
'gululkam.com.tm',
'ashgabatairport.gov.tm',
'altyn-kanun.com.tm',
'akgar.com.tm',
'msy.gov.tm',
'dana.com.tm',
'dana.edu.tm',
'metbugat.gov.tm',
'railway.gov.tm',
'bizbarde.com.tm',
'akyaprak.com.tm',
'fykmh.gov.tm',
'maryairport.gov.tm',
'islenen.com.tm',
'cct.com.tm',
'nurteh.com.tm',
'serhetabat-dovletabat.gov.tm',
'turkmensyyahat.gov.tm',
'danaproject.com.tm',
'tigirli-mahabat.com.tm',
'ta.com.tm',
'gnbookstore.com.tm',
'scct.gov.tm',
'archabilhotel.gov.tm',
'ticit.edu.tm',
'yarish.com.tm',
'burgutdesign.com.tm',
'sahysoltan.com.tm',
'sadaplast.com.tm',
'turkmentv.gov.tm',
'goshagumry.com.tm',
'artmuseum.gov.tm',
'dashdemir.com.tm',
'dayan.edu.tm',
'tizulgam.com.tm',
'tulm.gov.tm',
'tdmai.edu.tm',
'hekem.com.tm',
'salkyn.com.tm',
'bakgalhukuk.com.tm',
'aydyn-mahabat.com.tm',
'teykent.com.tm',
'saglyktm.com.tm',
'akbulut.com.tm',
'merdanatv.com.tm',
'hyzmatdashlar.com.tm',
'hazyna.com.tm',
'dashoguztravel.gov.tm',
'siyahatour.com.tm',
'ah-insurance.com.tm',
'dashoguzmuseum.gov.tm',
'chagalar-kitaphana.gov.tm',
'marymuseum.gov.tm',
'cefavaza2019.gov.tm',
'gala.com.tm',
'ttf.gov.tm',
'lebapmuseum.gov.tm',
'lebapkitap.gov.tm',
'dermanhana.com.tm',
'yovshan.com.tm',
'apteka.com.tm',
'balkanmuseum.gov.tm',
'deg.gov.tm',
'dovletkitaphana.gov.tm',
'caa.gov.tm',
'takykcesme.com.tm',
'ibcorp-saderatbank.com.tm',
'biznes.com.tm',
'business.com.tm',
'bt.com.tm',
'tia.gov.tm',
'getir.com.tm',
'iuhd.edu.tm',
'horjun.com.tm',
'marykitaphana.com.tm',
'turkmenteatrlary.gov.tm'];
    $notFound = [];

    foreach ($all as $key => $value) {
        foreach ($have as $has) {
            if ($value == $has) {
                unset($all[$key]);
            }
        }
    }

    return [$all];
    }
}
