<?php

namespace App\Http\Controllers;

use App\Hosting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OldHomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tests = DB::table('hostings_checked')->get();
        $http_code = $this->http_codes_explonation();

        return view('pages.home', compact('tests', 'http_code'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return *404* 'PageNotFound'
     */
    public function register() 
    {
        abort(404, 'Page Not Found');
    }

    /**
     * Return http_codes with explonation
     *
     * @return Array
     */
    public function http_codes_explonation() 
    {
        return [
            0   => 'Error: No status code',
            100 => 'Informational: Continue',
            101 => 'Informational: Switching Protocols',
            102 => 'Informational: Processing',
            200 => 'Successful: OK',
            201 => 'Successful: Created',
            202 => 'Successful: Accepted',
            203 => 'Successful: Non-Authoritative Information',
            204 => 'Successful: No Content',
            205 => 'Successful: Reset Content',
            206 => 'Successful: Partial Content',
            207 => 'Successful: Multi-Status',
            208 => 'Successful: Already Reported',
            226 => 'Successful: IM Used',
            300 => 'Redirection: Multiple Choices',
            301 => 'Redirection: Moved Permanently',
            302 => 'Redirection: Found',
            303 => 'Redirection: See Other',
            304 => 'Redirection: Not Modified',
            305 => 'Redirection: Use Proxy',
            306 => 'Redirection: Switch Proxy',
            307 => 'Redirection: Temporary Redirect',
            308 => 'Redirection: Permanent Redirect',
            400 => 'Client Error: Bad Request',
            401 => 'Client Error: Unauthorized',
            402 => 'Client Error: Payment Required',
            403 => 'Client Error: Forbidden',
            404 => 'Client Error: Not Found',
            405 => 'Client Error: Method Not Allowed',
            406 => 'Client Error: Not Acceptable',
            407 => 'Client Error: Proxy Authentication Required',
            408 => 'Client Error: Request Timeout',
            409 => 'Client Error: Conflict',
            410 => 'Client Error: Gone',
            411 => 'Client Error: Length Required',
            412 => 'Client Error: Precondition Failed',
            413 => 'Client Error: Request Entity Too Large',
            414 => 'Client Error: Request-URI Too Long',
            415 => 'Client Error: Unsupported Media Type',
            416 => 'Client Error: Requested Range Not Satisfiable',
            417 => 'Client Error: Expectation Failed',
            418 => 'Client Error: I\'m a teapot',
            419 => 'Client Error: Authentication Timeout',
            420 => 'Client Error: Enhance Your Calm',
            420 => 'Client Error: Method Failure',
            422 => 'Client Error: Unprocessable Entity',
            423 => 'Client Error: Locked',
            424 => 'Client Error: Failed Dependency',
            424 => 'Client Error: Method Failure',
            425 => 'Client Error: Unordered Collection',
            426 => 'Client Error: Upgrade Required',
            428 => 'Client Error: Precondition Required',
            429 => 'Client Error: Too Many Requests',
            431 => 'Client Error: Request Header Fields Too Large',
            444 => 'Client Error: No Response',
            449 => 'Client Error: Retry With',
            450 => 'Client Error: Blocked by Windows Parental Controls',
            451 => 'Client Error: Redirect',
            451 => 'Client Error: Unavailable For Legal Reasons',
            494 => 'Client Error: Request Header Too Large',
            495 => 'Client Error: Cert Error',
            496 => 'Client Error: No Cert',
            497 => 'Client Error: HTTP to HTTPS',
            499 => 'Client Error: Client Closed Request',
            500 => 'Server Error: Internal Server Error',
            501 => 'Server Error: Not Implemented',
            502 => 'Server Error: Bad Gateway',
            503 => 'Server Error: Service Unavailable',
            504 => 'Server Error: Gateway Timeout',
            505 => 'Server Error: HTTP Version Not Supported',
            506 => 'Server Error: Variant Also Negotiates',
            507 => 'Server Error: Insufficient Storage',
            508 => 'Server Error: Loop Detected',
            509 => 'Server Error: Bandwidth Limit Exceeded',
            510 => 'Server Error: Not Extended',
            511 => 'Server Error: Network Authentication Required',
            598 => 'Server Error: Network read timeout error',
            599 => 'Server Error: Network connect timeout error',
        ];
    }

    public function addHostings() {
        $hostings = [
            'takykcesme.com.tm',
            'ibcorp-saderatbank.com.tm',
            'iuhd.edu.tm',
            'balkanagyzsuw.gov.tm',
            'gepreg.gov.tm',
            'turkmenaltyn.com.tm',
            'aktam.com.tm',
            'dahua.com.tm',
            'awtomenzil.gov.tm',
            'avtoyollar.gov.tm',
            'akgap.com.tm',
            'turkmenhemrasy.gov.tm',
            'constructionprice.gov.tm',
            'giper.com.tm',
            'mlsp.gov.tm',
            'bazar.com.tm',
            'ashgabathyakimlik.gov.tm',
            'tdmi.edu.tm',
            'turkmenatlary.gov.tm',
            'lebaptravel.gov.tm',
            'strateg.gov.tm',
            'coca-cola.com.tm',
            'cci.com.tm',
            'turkmenpolat-bn.gov.tm',
            'industry.gov.tm',
            'tugu.gov.tm',
            'greatsilkroadconference2018.gov.tm',
            'turkmendomain.gov.tm',
            'onko.gov.tm',
            'kerwen.gov.tm',
            'terminal.gov.tm',
            'teronum.com.tm',
            'ecifas.gov.tm',
            'agb.com.tm',
            'harmantm.com.tm',
            'muk.com.tm',
            'hazarbalkan.com.tm',
            'turkmen-kaliy.com.tm',
            'altyn-kanun.com.tm',
            'fykmh.gov.tm',
            'islenen.com.tm',
            'serhetabat-dovletabat.gov.tm',
            'turkmensyyahat.gov.tm',
            'danaproject.com.tm',
            'tigirli-mahabat.com.tm',
            'ticit.edu.tm',
            'yarish.com.tm',
            'sahysoltan.com.tm',
            'dashdemir.com.tm',
            'merdanatv.com.tm',
            'hazyna.com.tm',
            'dashoguztravel.gov.tm',
            'siyahatour.com.tm',
            'dashoguzmuseum.gov.tm',
            'gala.com.tm',
            'dermanhana.com.tm',
            'yovshan.com.tm',
            'apteka.com.tm',
            'dovletkitaphana.gov.tm',
            'caa.gov.tm',
            'biznes.com.tm',
            'business.com.tm',
            'bt.com.tm',
            'online.tm',
            'tia.gov.tm',
            'getir.com.tm',
            'horjun.com.tm',
            'marykitaphana.com.tm',
            'museum.gov.tm',
            'turkmenteatrlary.gov.tm',
            'turkmenistan.gov.tm',
            'ashgabat2017.gov.tm',
            'politehnikum.edu.tm',
            'seysmostroy.gov.tm',
            'artmuseum.gov.tm',
            'senagatbank.gov.tm',
            'arzan.com.tm',
            'milligosun.gov.tm',
            'dost.com.tm',
            'oilgas.gov.tm',
            'halkbank.gov.tm',
            'st.com.tm',
            'tdp.gov.tm',
            'made-in-turkmenistan.com.tm',
            'mazam.com.tm',
            'mothercare.com.tm',
            'tmembassy.gov.tm',
            'mitsubishi.com.tm',
            'tmconsulate.gov.tm',
            'mission.gov.tm',
            'tdei.edu.tm',
            'tiztoleg.com.tm',
            'turkmenturkbank.gov.tm',
            'turkmenwater.com.tm',
            'tkm-derman.gov.tm',
            'muse.com.tm',
            'awtoulag.gov.tm',
            'sharafyabi.com.tm',
            'cultureofturkmenistan.gov.tm',
            'almaz-sheyh.com.tm',
            'tdob.gov.tm',
            'archa.com.tm',
            'balary.com.tm',
            'minenergo.gov.tm',
            'aksaray.com.tm',
            'gocdas.com.tm',
            'tstb.gov.tm',
            'tjk.com.tm',
            'meteo.gov.tm',
            'construction.gov.tm',
            'tkamm.gov.tm',
            'zenan.gov.tm',
            'dayhanbank.gov.tm',
            'insurance.gov.tm',
            'mfa.gov.tm',
            'tfeb.gov.tm',
            'tdh.gov.tm',
            'tbbank.gov.tm',
            'minagri.gov.tm',
            'turkmenhali.gov.tm',
            'turkmentextile.gov.tm',
            'stat.gov.tm',
            'minfin.gov.tm',
            'wekilbazardokma.gov.tm',
            'mintradefer.gov.tm',
            'migration.gov.tm',
            'minjust.gov.tm',
            'turkmencosmos.gov.tm',
            'tgymj.gov.tm',
            'exchange.gov.tm',
            'trsosh.edu.tm',
            'turkmenstandartlary.gov.tm',
            'saglykhm.gov.tm',
            'cci.gov.tm',
            'rysgalbank.com.tm',
            'tax.gov.tm',
            'turkmenexport.gov.tm',
            'bayramalytextilex.gov.tm',
            'nokat.com.tm',
            'yashlar.gov.tm',
            'turkmenfmd.gov.tm',
            'gujurlynesil.edu.tm',
            'turkmenhimiya.gov.tm',
            'sirius8.com.tm',
            'natureprotection.gov.tm',
            'nbp.com.tm',
            'science.gov.tm',
            'saylav.gov.tm',
            'influ.gov.tm',
            'telecom.tm',
            'acs.gov.tm',
            'mpi.gov.tm',
            'ib.gov.tm',
            'mb.gov.tm',
            'yosm.com.tm',
            'customs.gov.tm',
            'turkmenpost.gov.tm',
            'mincom.gov.tm',
            'turkmenbashiairport.com.tm',
            'tff.com.tm',
            'yashyldunya.com.tm',
            'awazasport.gov.tm',
            'galam.com.tm',
            'seyranasyyakhat.com.tm',
            'telekeci.com.tm',
            'wm.online.tm',
            'modelleroyi.gov.tm',
            'etalon.gov.tm',
            'doehler.com.tm',
            'hasyl.com.tm',
            'emart.com.tm',
            'tmcars.com.tm',
            'marysiyakhat.com.tm',
            'orient.tm',
            'bdo.com.tm',
            'gululkam.com.tm',
            'ashgabatairport.gov.tm',
            'akgar.com.tm',
            'msy.gov.tm',
            'dana.com.tm',
            'dana.edu.tm',
            'metbugat.gov.tm',
            'railway.gov.tm',
            'bizbarde.com.tm',
            'akyaprak.com.tm',
            'maryairport.gov.tm',
            'cct.com.tm',
            'nurteh.com.tm',
            'ta.com.tm',
            'gnbookstore.com.tm',
            'ashgabat2018.com',
            'scct.gov.tm',
            'archabilhotel.gov.tm',
            'burgutdesign.com.tm',
            'sadaplast.com.tm',
            'turkmentv.gov.tm',
            'goshagumry.com.tm',
            'dayan.edu.tm',
            'tizulgam.com.tm',
            'tulm.gov.tm',
            'tdmai.edu.tm',
            'dashoguzairport.gov.tm',
            'hekem.com.tm',
            'mir.tm',
            'salkyn.com.tm',
            'bakgalhukuk.com.tm',
            'aydyn-mahabat.com.tm',
            'teykent.com.tm',
            'saglyktm.com.tm',
            'akbulut.com.tm',
            'hyzmatdashlar.com.tm',
            'ah-insurance.com.tm',
            'chagalar-kitaphana.gov.tm',
            'marymuseum.gov.tm',
            'cefavaza2019.gov.tm',
            'ttf.gov.tm',
            'lebapmuseum.gov.tm',
            'lebapkitap.gov.tm',
            'balkanmuseum.gov.tm',
            'deg.gov.tm'
        ];
        foreach ($hostings as $hosting) {
            Hosting::create([
                'domain_name' => $hosting
            ]);   
        }

        return Hosting::all();
    }
}
